apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gaminganywhere-filter
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: karma98/gaminganywhere_ga-filter:latest
